list/urls.py
from django.urls import path

from list.views import (
    Index,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),

    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "list"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("list.urls", namespace="list")),
]

list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField(default="none")
    datetime = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(null=True, blank=True)
    done = models.BooleanField()
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name="tasks")

    def __str__(self):
        return self.content

list/views.py
from django.views import generic
from django.urls import reverse_lazy

from list.models import Task, Tag


class Index(generic.ListView):
    model = Task
    ordering = ['done', '-datetime']


class TaskCreateView(generic.CreateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('list:index')


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy('list:index')


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy('list:index')


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = '__all__'
    success_url = reverse_lazy('list:tag-list')


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy('list:tag-list')


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy('list:tag-list')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group mt-4">
  <li class="list-group-item"><a href="{% url 'list:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'list:tag-list' %}">Tags</a></li>
</ul>

templates/list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'list:tag-list' %}" class="btn btn-primary">Go back</a>
  </form>
{% endblock %}

templates/list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/tag_list.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="mt-4">
    Tags
    <a href="{% url 'list:tag-create' %}" class="btn btn-primary link-to-page float-right">
      Create
    </a>
  </h1>
  {% if tag_list %}
    <table class="table">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a href="{% url 'list:tag-update' pk=tag.id %}">Update</a></td>
          <td><a href="{% url 'list:tag-delete' pk=tag.id %}">Delete</a></td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no tag</p>
  {% endif %}
{% endblock %}

templates/list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'list:index' %}" class="btn btn-primary">Go back</a>
  </form>
{% endblock %}

templates/list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/task_list.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="mt-4">
    TODO list
    <a href="{% url 'list:task-create' %}" class="btn btn-primary link-to-page float-right">
      Create
    </a>
  </h1>
  {% if task_list %}

      {% for task in task_list %}
        <h3>
          {{ task.content }}
          {% if task.done == False %}
            <span class="text-danger">Not done</span>
          {% else %}
            <span class="text-success">Done</span>
          {% endif %}
        </h3>
      {% if task.done == False %}
          <a href="{% url 'list:task-update' pk=task.id %}" class="btn btn-success link-to-page float-right">
            Complete
          </a>
      {% else %}
        <a href="{% url 'list:task-update' pk=task.id %}" class="btn btn-secondary link-to-page float-right">
            Undo
          </a>
      {% endif %}
        <p>Created: {{ task.datetime }}</p>
        <p class="color-gray">Tags: home shop <a href="{% url 'list:task-update' pk=task.id %}">Update</a> <a href="{% url 'list:task-delete' pk=task.id %}">Delete</a></p>
      {% endfor %}

  {% else %}
    <p>There are no task</p>
  {% endif %}
{% endblock %}